config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "events#index"
  resources :events, only:[:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	belongs_to :user
	has_one_attached :image

	extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :genre
end

app/models/genre.rb
class Genre < ActiveHash::Base
  self.data = [
    { id: 0, name: '---' },
    { id: 1, name: 'AllGenre' },
		{ id: 2, name: 'REGGAE' },
		{ id: 3, name: 'HIPHOP' },
		{ id: 4, name: 'R&B' },
		{ id: 5, name: 'SOUL' },
		{ id: 6, name: 'SKA' },
		{ id: 7, name: 'SOKA' },
		{ id: 8, name: 'LATIN' },
		{ id: 9, name: 'DISCO' },
		{ id: 10, name: 'ROCK' },
		{ id: 11, name: 'TECHNO' },
		{ id: 12, name: 'EDM' },
		{ id: 13, name: 'CLASSIC' },
		{ id: 14, name: '歌謡曲' },
    { id: 15, name: 'JPOP' },
		{ id: 16, name: 'Others' }
  ]

  include ActiveHash::Associations
  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :user_name, presence: true
  PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i.freeze
  validates_format_of :password, with: PASSWORD_REGEX

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

	private
	def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up,
                                      keys: [:user_name])
	end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @event = Event.all.order('created_at DESC')
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
    if @event.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def event_params
    params.require(:event).permit(:event_name, :date, :open_time, :start_time, :place, :price_adv, :price_door, :capacity, :genre_id, :event_text, :precautions, :image).merge(user_id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/index.html.erb
<% @event.each do |event|%>
	<%= event.user.user_name %><br>
	<%= image_tag event.image.variant(resize: '500x500') %><br>
	<%= event.event_name %><br>
	<%= event.date %> <%= event.open_time %> <%= event.start_time %><br>
	place: @<%= event.place %> adv: ¥<%= event.price_adv %> door: ¥<%= event.price_door %><br>
	<%= event.event_text %><br>
<% end %>

app/views/events/new.html.erb
<%= form_with model: @event, url: events_path, local: true do |f| %>
<p>flyer</p>
<%= f.file_field :image %>
<p>event name</p>
<%= f.text_area :event_name %>
<p>event date</p>
<%= raw sprintf(
                  f.date_select(
                    :date,
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 2020,
                    end_year: 2030,
                    date_separator: '%s'),
                  "<p> / </p>", "<p> / </p>") %>
<p>open</p>
<%= f.time_select :open_time, prompt:true, ignore_data:true %>
<p>start</p>
<%= f.time_select :start_time, prompt:true, ignore_data:true %>
<p>place</p>
<%= f.text_area :place %>
<p>price(adv)</p>
<%= f.text_area :price_adv %>
<p>place(door)</p>
<%= f.text_area :price_door %>
<p>capacity</p>
<%= f.text_area :capacity %>
<p>genre</p>
<%= f.collection_select(:genre_id, Genre.all, :id, :name, {} ) %>
<p>contents</p>
<%= f.text_area :event_text %>
<p>precautions</p>
<%= f.text_area :precautions %>
<%= f.submit "send" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EasyReserve</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Easy Reserve</h1>
      <%= link_to "New Event", new_event_path %>
      <% if user_signed_in? %>
        <%= "#{current_user.user_name}" %>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "新規登録", new_user_registration_path %>
        <%= link_to "ログイン", new_user_session_path %>
      <% end %>
    </header>
    <%= yield %>
  </body>
</html>